# Site settings
title: GitHub Repository Test Site
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  While it may only be a test site, it still contains swirls of awesome sauce.
baseurl: "netlify" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  hilery

# Build settings
markdown: kramdown
